### ISSUE TITLE
Bug 反馈 - [大佬 执行后报错]

### ISSUE THREAD

**Issue by Yakumo-Yukari** [XcantloadX/AutoCloudSign#16]
执行后日志里就是这个

``` PHP Fatal error:  Uncaught ReflectionException: Class DefaultScriptStorage does not exist in /www/wwwroot/AutoCloudSign/vendor/nette/php-generator/src/PhpGenerator/ClassType.php:110
Stack trace:
#0 /www/wwwroot/AutoCloudSign/vendor/nette/php-generator/src/PhpGenerator/ClassType.php(110): ReflectionClass->__construct()
#1 /www/wwwroot/AutoCloudSign/lib/confhelper.php(36): Nette\PhpGenerator\ClassType::from()
#2 /www/wwwroot/AutoCloudSign/lib/confhelper.php(72): ConfHelper::fromDefaultStorage()
#3 /www/wwwroot/AutoCloudSign/start.php(6): ConfHelper::init()
#4 {main}
  thrown in /www/wwwroot/AutoCloudSign/vendor/nette/php-generator/src/PhpGenerator/ClassType.php on line 110

Fatal error: Uncaught ReflectionException: Class DefaultScriptStorage does not exist in /www/wwwroot/AutoCloudSign/vendor/nette/php-generator/src/PhpGenerator/ClassType.php:110
Stack trace:
#0 /www/wwwroot/AutoCloudSign/vendor/nette/php-generator/src/PhpGenerator/ClassType.php(110): ReflectionClass->__construct()
#1 /www/wwwroot/AutoCloudSign/lib/confhelper.php(36): Nette\PhpGenerator\ClassType::from()
#2 /www/wwwroot/AutoCloudSign/lib/confhelper.php(72): ConfHelper::fromDefaultStorage()
#3 /www/wwwroot/AutoCloudSign/start.php(6): ConfHelper::init()
#4 {main}
  thrown in /www/wwwroot/AutoCloudSign/vendor/nette/php-generator/src/PhpGenerator/ClassType.php on line 110
----------------------------------------------------------------------------
★[2022-08-03 19:53:12] Successful
----------------------------------------------------------------------------
```

**Comment by XcantloadX** [comment]
你这是在什么环境下运行的？我复现不了

**Comment by Yakumo-Yukari** [comment]
> 你这是在什么环境下运行的？我复现不了

我用的 ubuntu  php7.4   

大佬 我使用腾讯云函数部署也不成功呢，对了 大佬腾讯云函数好像更新了和你的教程有一些出入 可以更新一下么 根据你教程上传后 提示  

<html>
<body>


2022-08-04 18:28:28 | 控制台 | 操作失败
-- | -- | --
函数创建中...函数创建失败, 失败原因：未在根目录下找到函数执行入口文件，请确认代码包入口文件名和 handler 设置是否对应或代码压缩包是否正常。


</body>
</html>

**Comment by Yakumo-Yukari** [comment]
大佬  我用腾讯云函数创建  开始那个问题  使用 文件夹上传解决了  但是后面 不管选择PHP7.2  还是7.4  都测试不成功   是不是账号的配置文件也改了呢？可以更新下云函数的教程和账号配置的教程吗
